services:
  api:
    container_name: "printscript-service-api"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: ${USERNAME}
        TOKEN: ${TOKEN}
    environment:
      REDIS_HOST: redis-bus
      REDIS_PORT: 6379

    ports:
      - 8003:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: printscript_db
    image: postgres:16
    ports:
      - 5435:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-bus:
    image: redis:6-alpine
    container_name: "redis_bus_dev"
    ports:
      - "6379:6379"

volumes:
  pgdata: