spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

auth0:
  audience: ${AUTH0_AUDIENCE}

asset:
  service:
    url: ${ASSET_SERVICE_URL}

services:
  authorization:
    url: ${AUTHORIZATION_SERVICE_URL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

stream:
  formatting:
    request:
      key: formatting-requests
    result:
      key: formatting-results
  linting:
    request:
      key: linting-requests
    result:
      key: linting-results
  testing:
    request:
      key: testing-requests
    result:
      key: testing-results
  consumer:
    group: printscript-service-group
